---
name: on_hello_event1
pack: amsterdam_st2
description: Sample rule firing on amsterdam_st2.event1.
enabled: true
trigger:
    type: amsterdam_st2.event1
action:
    ref: amsterdam_st2.greet
    parameters:
        greeting: Yo
